### ISSUE TITLE
React 19 makes for huge icons

### ISSUE THREAD

**Issue by Vacilando** [ismamz/react-bootstrap-icons#69]
In NextJS 15, after upgrading to React 19, the icons grow huge and do not have the right color, eg:
`<ChevronRight className="scale-75 text-gray-500" />`

**React 18**

<img width="107" alt="image" src="https://github.com/user-attachments/assets/02569695-478d-4a25-af2b-e555aff2b41a">

**React 19**

<img width="914" alt="image" src="https://github.com/user-attachments/assets/59b70546-3d59-40ed-afe4-d83c930616dd">

**Comment by jbothma** [comment]
I notice the `width="1em" height="1em" fill="currentColor"` attributes are gone after the upgrade. Trying to figure out why.

**Comment by jbothma** [comment]
seems to be because defaultProps for functional components has been deprecated for a while, was possibly removed in react 18.3, and maybe next.js patched over it until next.js 15? 

https://github.com/vercel/next.js/discussions/52522
https://medium.com/@tempmailwithpassword/managing-default-props-next-js-deprecation-the-end-of-function-components-876bd551c01c
